/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platforms_Types.h"

#define RCC_BASE 0x40021000
#define GPIOA_BASE 0x40010800

#define RCC_APB2ENR (*(volatile uint32 * )(RCC_BASE + 0x18))
#define GPIOA_CRH   (*(volatile uint32 * )(GPIOA_BASE + 0x04))
#define GPIOA_ODR   (*(volatile uint32 * )(GPIOA_BASE + 0x0C))

typedef union {
	vuint32 all_fields ;
	struct{
		vuint32 pin0:1 ;
		vuint32 pin1:1 ;
		vuint32 pin2:1;
		vuint32 pin3:1;
		vuint32 pin4:1;
		vuint32 pin5:1;
		vuint32 pin6:1;
		vuint32 pin7:1;
		vuint32 pin8:1;
		vuint32 pin9:1;
		vuint32 pin10:1;
		vuint32 pin11:1;
		vuint32 pin12:1;
		vuint32 pin13:1;
		vuint32 pin14:1;
		vuint32 pin15:1;
		vuint32 pin16:1;
		vuint32 pin17:1;
		vuint32 pin18:1;
		vuint32 pin19:1;
		vuint32 pin20:1;
		vuint32 pin21:1;
		vuint32 pin22:1;
		vuint32 pin23:1;
		vuint32 pin24:1;
	}pin;
}R_ODR_t;
volatile R_ODR_t*  R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0C);
int main(void){

	RCC_APB2ENR |= 1<<2 ;
	GPIOA_CRH &= 0xff0fffff ;
	GPIOA_CRH |= 0x00200000 ;
	while(1)
	{
		//GPIOA_ODR |= 1<<13 ; // set bit 13
		R_ODR->pin.pin13 = 1 ;
		for (int i =0 ;i<5000;i++);//wait
		//GPIOA_ODR &= ~(1<<13) ; // clear bit 13
		R_ODR->pin.pin13 = 0 ;
		for (int i =0 ;i<5000;i++);//wait

	}

}
